name: Build & Release PHAR + Docker

on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags like v1.0.0

jobs:
  build-and-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: phar

      - name: Build PHAR
        run: php -d phar.readonly=0 build-phar.php

      - name: Rename PHAR for release (remove .phar)
        run: |
          mv movdl.phar movdl
          chmod +x movdl

      - name: Create release archives
        run: |
          zip -r movdl.zip movdl
          tar -czf movdl.tar.gz movdl

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            movdl
            movdl.zip
            movdl.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/movdl:latest
