name: Build & Release PHAR + Docker

on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags like v1.0.0

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: phar
          tools: composer

      - name: Install dependencies (if using Composer)
        run: |
          if [ -f composer.json ]; then composer install --no-dev; fi

      - name: Build PHAR
        run: php -d phar.readonly=0 build-phar.php

      - name: Rename PHAR for release (remove .phar)
        run: |
          mv movdl.phar movdl
          chmod +x movdl

      - name: Create release archives
        run: |
          zip -r movdl.zip movdl
          tar -czf movdl.tar.gz movdl

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            movdl
            movdl.zip
            movdl.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-release:
    runs-on: ubuntu-latest
    needs: build-release

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/movdl:latest

